server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_coinnect
    username: root
    password: 35828889Ped.
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  doc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true

  cors:
    origin-patterns:
      - http://localhost:8080
      - http://localhost:3000

  receitaws:
    token: ${RECEITAWS_TOKEN}

  openroute:
    api-key: ${OPENROUTE_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, beans, env, configprops  # Expondo alguns endpoints do Actuator
  endpoint:
    health:
      show-details: always  # Exibe detalhes no endpoint de saúde
  server:
    port: 8081  # Definindo uma porta diferente para o Actuator, caso queira
